### PR TITLE
Fixcount

### PR DESCRIPTION
**Pull request by cloudformdesign**
Added new tests to test for bug when counting in parallel

Fixed counting in parallel

### CODE REVIEW

**Comment by mattdodge** [comment]
This needs to be moved over to the counter repo and not the util repo I think

**Comment by cloudformdesign** [comment]
I believe it has been moved and merged


   1. BLK-146 <https://neutralio.atlassian.net/browse/BLK-146>

**Comment by cloudformdesign** [comment]
feel free to close it out

**Comment by mattdodge** [comment]
Yeah, looks like it was merged by nio-blocks/counter#5

**Pull request closed without merging**
