### PR TITLE
Added value command. Sends back data in the text

### PR DESCRIPTION
**Pull request by cloudformdesign**
https://neutralio.atlassian.net/browse/BLK-164

### CODE REVIEW

**Comment by hansmosh** [comment]
This is looking good but it's not longer able to be merged on github. Please update. I'll be sure to get it merged quickly after so that this doesn't happen again.

**Comment by mattdodge** [comment]
This shouldn't be done on the util repo, these issues need to be recreated on the respective repos. I will do that and link

**Comment by mattdodge** [comment]
Actually, scratch that. These changes have already been committed and the submodules are updated. Closing this out

**Comment by cloudformdesign** [comment]
thanks matt.

**Pull request closed without merging**
